### ISSUE TITLE
InitialStateConfiguration.lastKnownStateFromJournal, and Error continuing

### ISSUE THREAD

**Issue by badboy2174** [mzheravin/exchange-core#59]
![1](https://user-images.githubusercontent.com/44084878/84708661-7c60e680-af93-11ea-8954-9c0377321f85.png)
String exchangeId = "MY_EXCHANGE" ;
		long snapshotBaseSeq = 0 ;
ExchangeConfiguration conf = ExchangeConfiguration.defaultBuilder()
				.serializationCfg(SerializationConfiguration.DISK_JOURNALING)
			.initStateCfg(InitialStateConfiguration.lastKnownStateFromJournal(exchangeId, 1, snapshotBaseSeq))
				.build() ;
--------------------------------------------------------
And then start the program. And when I add users and orders, It go to error below:
java.lang.IllegalStateException: File already exists: .\dumps\MY_EXCHANGE_journal_1_0001.ecj
	at exchange.core2.core.processors.journaling.DiskSerializationProcessor.startNewFile(DiskSerializationProcessor.java:694) ~[classes/:na]
	at exchange.core2.core.processors.journaling.DiskSerializationProcessor.writeToJournal(DiskSerializationProcessor.java:270) ~[classes/:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor-3.4.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]

**Comment by mzheravin** [comment]
Hi,
This scenario was not covered indeed.
This needs to be fixed, thanks for reporting.

**Comment by tvassiliadis** [comment]
Hi, I guess this bug still persists.

**Comment by bcashier** [comment]
The goal is to skip loading snapshot datas if this one doesn't exists and keep the exchange-core launching without taking it in count.
